version: "3.8"

services:
  blogging-service:
    build: ./blogging-service
    networks:
      - backend
    environment:
      - DB_HOST=blogging-db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=root123
      - DB_NAME=finki-blogger-blogs
    deploy:
      mode: replicated
      replicas: 1
      endpoint_mode: vip

  comment-service:
    build: ./CommentService
    networks:
      - backend
    environment:
      - DB_HOST=blogging-db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=root123
      - DB_NAME=finki-blogger-blogs
    deploy:
      mode: replicated
      replicas: 1
      endpoint_mode: vip

  like-service:
    build: ./likeService
    networks:
      - backend
    environment:
      - DB_HOST=blogging-db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=root123
      - DB_NAME=finki-blogger-blogs
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
    deploy:
      mode: replicated
      replicas: 1
      endpoint_mode: vip
    depends_on:
    - rabbitmq

  email-service:
    build: ./emailService
    networks:
      - backend
    environment:
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SPRING_RABBITMQ_PORT=5672
    deploy:
      mode: replicated
      replicas: 1
      endpoint_mode: vip
    depends_on:
     - rabbitmq

  jwt-service:
    build: ./JWT-service
    networks:
      - backend
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://jwt-db:5432/finki-blogger-jwt
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=root123
    deploy:
      mode: replicated
      replicas: 1
      endpoint_mode: vip

  frontend:
    build: ./frontend
    ports:
      - "4200:4200"
    networks:
      - frontend
    depends_on:
      - api-gateway

  api-gateway:
    image: kong:latest
    environment:
      KONG_DATABASE: "off"
      KONG_DECLARATIVE_CONFIG: /app/kong.yml
    volumes:
      - ./kong.yml:/app/kong.yml
    ports:
      - "8000:8000"
    networks:
      - frontend
      - backend

  blogging-service-lb:
    image: nginx:latest
    volumes:
      - ./nginx/blogging-service.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8086:80"
    networks:
      - backend
    depends_on:
      - blogging-service

  comment-service-lb:
    image: nginx:latest
    volumes:
      - ./nginx/comment-service.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8087:80"
    networks:
      - backend
    depends_on:
      - comment-service

  like-service-lb:
    image: nginx:latest
    volumes:
      - ./nginx/like-service.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8088:80"
    networks:
      - backend
    depends_on:
      - like-service

  email-service-lb:
    image: nginx:latest
    volumes:
      - ./nginx/email-service.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8089:80"
    networks:
      - backend
    depends_on:
      - email-service

  jwt-service-lb:
    image: nginx:latest
    volumes:
      - ./nginx/jwt-service.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8090:80"
    networks:
      - backend
    depends_on:
      - jwt-service

  blogging-db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root123
      POSTGRES_DB: finki-blogger-blogs
    volumes:
      - blogging-db-data:/var/lib/postgresql/data
    networks:
      - backend

  jwt-db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root123
      POSTGRES_DB: finki-blogger-jwt
    volumes:
      - jwt-db-data:/var/lib/postgresql/data
    networks:
      - backend

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - backend

networks:
  frontend:
  backend:

volumes:
  blogging-db-data:
  jwt-db-data:
